### ISSUE TITLE
Polymer Starter Kit Error.

### ISSUE THREAD

**Issue by samcarecho** [vguillou/parallax-element#1] opened 2015-11-24 17:08 UTC
After adding parallax-element to the latest version of Polymer Starter Kit (PSK v1.1.1 - Polymer V1.2.0), the following error shows in the console. Might this be a bug?

https://gist.github.com/samcarecho/4cc6b7a7eff9bff30779

**Comment by vguillou** [comment] 2015-11-24 23:32
Hello!

I couldn't reproduce this issue. Could you provide more context/snippets ?
I also ran the demos with the latests dependencies, including the <a href="http://vguillou.github.io/webcomponents/parallax-element/demo/demo-paper-scroll-header-panel.html">paper-scroll-header-panel</a> demo (<a href="https://github.com/vguillou/parallax-element/blob/master/demo/demo-paper-scroll-header-panel.html">source</a>), and it works  properly.

Polymer Starter Kit being based on a &lt;paper-scroller-header-panel&gt;, i recommend that you take a look at this demo and try to implement it the same way.
I'll try whenever i find the time in the coming weeks.

Keep me up to date ! :ok_hand:

**Comment by vguillou** [comment] 2015-12-06 22:55
So I've been busy testing the integration into Polymer Starter Kit 1.2.0, and it went well. Here is what I came up with : <a href="https://github.com/vguillou/vguillou.github.io/tree/master/examples/PSK_with_parallax_layers">here</a>

To sum it up, I took all the main content of the `paper-drawer` and made a new component for it. This way, I could use the `ParallaxScrollerBehavior` to make the `paper-scroll-header-panel` condense properly when scrolling. Of course, it also involve moving around a bit of JS and CSS. Take a look at the link above for to see the code.

Anyway, I didn't run into the error you encountered.
So unless you can give me more detail, I'll probably close the issue in some weeks. :+1:

**Comment by vguillou** [comment] 2016-01-13 08:45
Closed as i couldn't reproduce the issue, and provided a working implementation.
Re-open if you think it's necessary !

**Comment by vguillou** [comment] 2016-01-13 08:46
Closed as there's no activity here for more than a month, and i couldn't reproduce the issue (but provided a working implementation).
Re-open if you think it's necessary !

**Closed as completed by vguillou** 2016-01-13 08:46 UTC

**Comment by samcarecho** [comment] 2016-01-13 15:41
@vguillou I'm really sorry for the delay on replying.
The notification emails got lost among many others.

I got it to work properly. Thanks!
